### ISSUE TITLE
Example outdated in README

### ISSUE THREAD

**Issue by massimoforni** [KoenZomers/UniFiApi#11]
Hello,
After 1.1.4.0 I see you removed the IDisposable interface for the Api class (https://github.com/KoenZomers/UniFiApi/commit/e9da049c62a5f473e81ce385f276d5ca51336ae4) which in turns renders the README example outdated since it indicate to use the "using" statement (using can be used only with classes that implements the IDisposable interface)

It also renders the Console Project not being able to be built in VS

Thank you

**Comment by KoenZomers** [comment]
Thanks for bringing this to my attention @massimoforni. You're absolutely correct. I have updated the code already and will update the code sample on GitHub in a minute.
