### ISSUE TITLE
Session Timeout

### ISSUE THREAD

**Issue by Shulyakovskiy** [KoenZomers/UniFiApi#12]
Hi.
How to set the session time before blocking during client authorization.
Simple Code             
var obj = new UnifiCmdRequest { cmd = "authorize-guest", mac = mac, minutes = 60.ToString() };

**Comment by KoenZomers** [comment]
Not sure if I fully understand your question @Shulyakovskiy. If you mean how to apply a custom timeout on the connection towards UnIFi when using the `AuthorizeGuest` method, you can simply change the public property `ConnectionTimeout `on your Api instance to modify this. By default it's set to 60.000 milliseconds which means a 60 seconds timeout period.

Does this answer your question?

**Comment by Shulyakovskiy** [comment]
I mean the time to re-authorize the user on the router, for example, after 60 minutes, disable

**Comment by KoenZomers** [comment]
You mean this option then, right?

![image](https://user-images.githubusercontent.com/5940670/60570574-2854f600-9d72-11e9-8594-d1775b03f1fc.png)

This is a global setting on your UniFi controller and can't be provided with each individual request.
