### ISSUE TITLE
Issue when retrieving connection times 

### ISSUE THREAD

**Issue by MearTechnology** [KoenZomers/UniFiApi#13]
Hi, 
When retrieving times such as "First seen" it does not return actually the date and time the device has been seen.

Is it possible to add the session time start and session time end to Getclienthistory?

Thank you so much in advance.

Also, not related to the Library, do you have any way we can make donations as appreciation for your work?

Regards

**Comment by KoenZomers** [comment]
Thanks for letting me know. I'll look into it.

**Comment by KoenZomers** [comment]
I think I managed to capture all your requests in version 1.1.6.0. Please check the [release notes](https://github.com/KoenZomers/UniFiApi#version-history) for specifics on the changes I've done. Let me know in case I missed something.

As for donations, I appreciate the offer. I've never done that before, so not sure how to deal with that best. I've opened up https://paypal.me/koenzomers through which you could send a donation to see if that works well. Thanks in advance!

**Comment by MearTechnology** [comment]
Hi, 

I've just tested and it is working fine. :) 

Thanks for this.

P.S - sent your details to our accounts.
