### ISSUE TITLE
[request] get some more data from devices

### ISSUE THREAD

**Issue by MearTechnology** [KoenZomers/UniFiApi#14]
Hi, 
Can you please add this to the access point responses?

`        /// <summary>
        /// Device Adopted
        /// </summary>
        [JsonProperty(PropertyName = "adopted")]
        public string Adpoted { get; set; }

        /// <summary>
        /// Serial Number of the access point
        /// </summary>
        [JsonProperty(PropertyName = "serial")]
        public string SerialNumber { get; set; }

        /// <summary>
        /// Device Uptime
        /// </summary>
        [JsonProperty(PropertyName = "uptime")]
        public string Uptime { get; set; }

        /// <summary>
        /// Device Model
        /// </summary>
        [JsonProperty(PropertyName = "model")]
        public string Model { get; set; }

        /// <summary>
        /// Device Host name
        /// </summary>
        [JsonProperty(PropertyName = "hostname")]
        public string Hostname { get; set; }

        /// <summary>
        /// Device Type
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Device Adopt IP
        /// </summary>
        [JsonProperty(PropertyName = "adopt_ip")]
        public string AdoptIP { get; set; }
        
        /// <summary>
        /// Device ID
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string id { get; set; }`

Don't want to be forking your project :)

**Comment by KoenZomers** [comment]
Added in version 1.1.7.0. Please consider forking anyway and doing a Pull Request to add stuff like this. Makes it easier for me to accept it :)
