### ISSUE TITLE
Enable / Disable SSID

### ISSUE THREAD

**Issue by supercop89** [KoenZomers/UniFiApi#15]
Hi KoenZomers!

Nice and professionell work.

Do you have any change to integrate the functionality for enabling/disabling a known SSID?

Therefore it would be possible to enable and disable the wlan via the API.

**Comment by KoenZomers** [comment]
Thanks.

Can you explain me where I would do this through the web interface of UniFi? Then I can probably add it to the library as well.

**Comment by supercop89** [comment]
You mean in the controller?

https://community.ui.com/questions/How-to-disable-5ghz-on-AP-AC-LR-over-Unifi-software-controller-Browser/a3b7b903-d71f-4fc6-9d1d-f0b6a8fc3f65

**Comment by KoenZomers** [comment]
So you really mean to say you want to automate using this switch?

![image](https://user-images.githubusercontent.com/5940670/62763357-9f755c80-ba8b-11e9-819e-44d951710614.png)

Just out of curiosity, what would be the use case you have for it to want to do this in an automated way?

**Comment by KoenZomers** [comment]
Closing as no response received.
