### ISSUE TITLE
[BUG] Not all Networks are loading

### ISSUE THREAD

**Issue by Sander0542** [KoenZomers/UniFiApi#20]
**Describe the bug**
When I try to fetch my networks only my LAN network shows up. The other networks don't have certain properties from the API, this means the object is not parsed.

**To Reproduce**
1. Create a Api client
2. Login using username and password
3. Fetch all the networks using the `GetNetworks()` method.

**Expected behavior**
A list of all the networks, not just the LAN network.

**Versions (please complete the following information):**
- OS: Windows 10
- UniFiApi: 1.1.9
- Unifi Controller: 6.1.71

**Comment by KoenZomers** [comment]
Hi @Sander0542. Unfortunately I do not have access to such an environment, so I cannot troubleshoot it. If you can and are willing to privately share an account where I could reproduce this, I can look into it, otherwise I'm afraid there's nothing I can do.

**Comment by KoenZomers** [comment]
Closing as no further feedback has been received.
