### ISSUE TITLE
Password with special characters

### ISSUE THREAD

**Issue by Master-Silver** [KoenZomers/UniFiApi#24]
The login over this Api on the UniFi controller will fail, when the used password contains a ". Not exactly sure why it fails, but UniFi allows such passwords.

**Comment by KoenZomers** [comment]
Thanks for reporting! That should be easy enough to reproduce and fix. I'll look into it.

**Comment by KoenZomers** [comment]
The dot doesn't seem to be the issue. Are there more special characters in the password? I'll try some of those.

**Comment by KoenZomers** [comment]
Also that seems to work well. I.e. I created a temporary account with the password `Jemsf%_&Sk#fek.34324` and it authenticated without any problems. Can you provide more information on what exactly goes wrong and against what kind of UniFi controller you are authenticating? Is it self hosted, cloud hosted, cloud key, which version, etc?

**Comment by Master-Silver** [comment]
> Jemsf%_&Sk#fek.34324

does not contain any quotation mark (" or '). I had trouble with a password that contains quotation marks. I think it has to do with the escaping before sending the login details per Json to the controller.
I have a self hosted controller, but the login worked in the browser just not with the API. I also checked my code with the debugger, the password was correct before sending it to the controller.

**Comment by KoenZomers** [comment]
Ah I read your message as the dot being the guilty one, not the quotes. Let me try it with the quotes as well.

**Comment by KoenZomers** [comment]
Found the issue. Releasing a fix for it now.

**Comment by KoenZomers** [comment]
Fixed in version 1.1.10.1. Thanks for reporting it.
