### ISSUE TITLE
Please add the possibility to specify a Site ID

### ISSUE THREAD

**Issue by scheelings** [KoenZomers/UniFiApi#4]
I just tested this API and the device list and client list were empty. I noticed that the URL's are hard coded and all point to the Default Site in the Unifi controller. Because I am using another Site than the Default Site, the list with devices/clients is empty.
Can you add a Site parameter in the constructor of the API (with perhaps a default value of "default") and use this parameter in the URL's (by replacing /default/ with /{SiteId}/) or some other kind of solution?

Thanks,
Danny

**Comment by KoenZomers** [comment]
Good one. I'll have a look at this.

**Comment by KoenZomers** [comment]
@scheelings, I don't have a second site to test this again. If I just create a new site in UniFi, it seems to randomly generate a combination of letters and digits as the site ID. Is that correct? In that case it would suffice to accept a string somewhere to provide the correct site identifier. Do you agree?

**Comment by KoenZomers** [comment]
I've pushed version 1.0.2.0 in which you can provide the site ID through the constructor. Can you test if this works well on your multi site setup?

**Comment by scheelings** [comment]
Yes, I agree to use some kind of SiteID. I downloaded your code and implemented this in my downloaded code, so I could continue my development. I’ll check your code tomorrow and will leave a comment here!

**Comment by KoenZomers** [comment]
Perfect, thanks!

**Comment by scheelings** [comment]
I just checked your code and it looks the same as my code, so this should work fine!

**Comment by KoenZomers** [comment]
Thanks for confirming and addressing! Will close this issue.
