### ISSUE TITLE
KoenZomers.Tools.UniFi.Api doesn't seem to exist

### ISSUE THREAD

**Issue by MearTechnology** [KoenZomers/UniFiApi#8]
Can you please help? 

Cheers.

**Comment by MearTechnology** [comment]
Managed to find out.

using (var UnifiApp = new KoenZomers.UniFi.Api.Api(new Uri("https://ulr:8443"), "siteid
"))

Do I have any way of listing all sites?

**Comment by KoenZomers** [comment]
@MearTechnology, I believe there is no such method yet, but it would be easy to add. Let me look into this for you a little later.

**Comment by MearTechnology** [comment]
@KoenZomers 
Thank you very much for that. :)

**Comment by KoenZomers** [comment]
I've added a function called GetSites() in version 1.1.1.0. Can you check if that is what you are looking for?

**Comment by MearTechnology** [comment]
Yes, just updated to the latest version and that's it! 👍 

Thank you very much.

**Comment by MearTechnology** [comment]
Is it possible to add functionality so we can see a certain device history through the API?

**Comment by KoenZomers** [comment]
Added in version 1.1.2.0. I welcome you if you are a developer yourself to contribute to this open source solution by forking it, adding additional methods and submitting a pull request. I'll then be happy to merge your submission with this code so others can benefit from it as well.

**Comment by MearTechnology** [comment]
Thank you very much for that.

Yes, I am a developer, I didn't want to mess with your work. 

I will surely do it.

Thanks again.

**Comment by KoenZomers** [comment]
No worries, I appreciate it if you try at least and will check it first before accepting the PR :)
